### ISSUE TITLE
9/20 회의 안건

### ISSUE THREAD

**Issue by adriner2640** [CroatiaTeam/Bussiness#2]
> 9/20 회의 안건 정해봅시다.

**Comment by adriner2640** [comment]
@adriner2640 개발 방향

**Comment by 2DU** [comment]
1.맵 재 개편
2.개발 현황, 계획

**Comment by flygfour** [comment]
1.주말마다 주간 개발 계획 수립, (이번주는 어디어디 챕터까지 진도를 빼고, 그럴러면 기획팀은 어디어디까지 시나리오를 작성하고, 인게임 개발팀은 어떤어떤 몹까지 만들고, 어떤어떤 시스템을 구현해야한다) 정도로 구체적으로 세웁시다

2.맵을 갈아엎을까요 말까요

**Comment by flygfour** [comment]
에... 언제할건지 시간 정합시다.

**Comment by flygfour** [comment]
3.현재 인게임 개발인원이 턱없이 부족(이라기보단 안하는것같네요)한데 이 문제에 대한 해결 방침 의논

**Comment by malangbalam** [comment]
프로그래밍팀 디자인 가이드라인 정해야죠?

**Comment by adriner2640** [comment]
@malangbalam 가이드라인 정해야해요

**Comment by adriner2640** [comment]
정이해주실분 구합니다.

**Comment by ssjy806** [comment]
^ 정리해주실분 구합니다

**Comment by malangbalam** [comment]
1.맵 재 개편
2.개발 현황, 계획
3.주말마다 주간 개발 계획 수립, (이번주는 어디어디 챕터까지 진도를 빼고, 그럴러면 기획팀은 어디어디까지 시나리오를 작성하고, 인게임 개발팀은 어떤어떤 몹까지 만들고, 어떤어떤 시스템을 구현해야한다) 정도로 구체적으로 세웁시다
4.맵을 갈아엎을까요 말까요
5.프로그래밍팀 디자인 가이드라인

**Comment by 2DU** [comment]
http://ctwiki.dothome.co.kr/dokuwiki/doku.php?id=9월_20일_회의_주제

**Comment by adriner2640** [comment]
https://github.com/CroatiaTeam/Bussiness/blob/master/%ED%9A%8C%EC%9D%98/%EC%95%88%EA%B1%B4/2015.09.20.md

**Comment by adriner2640** [comment]
@adriner2640 이번 주 회의 결과
안건 1 맵 개편의 관한 내용
  - 제로베이스에서 처음부터 다시
안건 2 주말마다 주간 개발 계획 수립1)
안건 3 현재 인게임 개발인원이 턱없이 부족2)한데 이 문제에 대한 해결 방침 의논
 - 다음 주
안건 4 프로그래밍팀 디자인 가이드라인
안건 5 세계관 방을 검수방으로 전향하는 데에 대한 안건
 - 지금 세계관방을 검수방으로 전향
안건 6 정리해고
 - 다음주
안건 7 추가된 서버 자원 활용 방안
 - Beta서버 사용
안건 8 건축관련
 - 안건1과 동일
